import type { Metadata } from "next";
import { Kanit, Playfair_Display, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["900"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} ${playfairDisplay.variable} ${geistMono.variable} antialiased bg-cover bg-center bg-no-repeat bg-fixed min-h-screen flex flex-col`}
        style={{ backgroundImage: "url(/assets/romantic.jpg)" }}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
